goparty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
admin.site.site_header = "GoParty Admin"
admin.site.site_title = "GoParty Admin Portal"
admin.site.index_title = "Welcome to GoParty Admin Portal"

home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('login', views.my_login, name = 'login'),
    path('logout', views.my_logout, name = 'logout'),
    path('signup', views.my_signup, name = 'signup'),
    path('view_profile', views.view_profile, name = 'view_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('delete_profile', views.delete_profile, name='delete_profile'),
    path('restaurant/<str:name>', views.restaurant, name = 'restaurant'),
    path('city/<str:city>', views.bycity, name = 'bycity'),
    ]

home/models.py
from pyexpat import model
from statistics import mode
from django.db import models
from django_google_maps import fields
from django.contrib.auth.models import User

# Create your models here.

class Restaurant(models.Model):
    name = models.CharField(max_length=100, unique=True)
    address = fields.AddressField(max_length=200)
    geolocation = fields.GeoLocationField(max_length=100)
    price = models.IntegerField(default=1000, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    district = models.CharField(max_length=100, blank=True, null=True)
    contact = models.BigIntegerField(blank=True, null=True)
    pincode = models.IntegerField(blank=True, null=True)
    edited = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    created = models.DateTimeField(auto_now=True, blank=True, null=True)
    

    def __str__(self):
        return self.name

class RestaurantImage(models.Model):
    image = models.ImageField(upload_to = 'restaurant_images/')
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name="images")

class RestaurantFeature(models.Model):
    restaurant = models.OneToOneField(Restaurant, on_delete=models.CASCADE, related_name="features")
    great_food = models.BooleanField(default=True)
    satisfactory_staff = models.BooleanField(default=True)
    great_ambience = models.BooleanField(default=True)
    good_service = models.BooleanField(default=True)
    resonable_cost = models.BooleanField(default=True)
    hygiene_and_cleanliness = models.BooleanField(default=True)

    def __str__(self):
        return self.restaurant.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default = 'user/profile/default_user.jpg', upload_to = 'user/profile/%Y/%m/%d/')
    
    def __str__(self):
        return self.user.username

class Featured(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name="featureds")

    def __str__(self):
        return self.restaurant.name

home/views.py
from unicodedata import name
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth import login, authenticate, logout
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# Create your views here.

def get_search_results(input):
    restaurants = Restaurant.objects.filter(Q(name = input) | Q(city = input) | Q(district = input) | Q(address__contains = input) | Q(state = input))
    return restaurants

def index(request):
    if request.method == "POST":
        # try:
            input = request.POST["input"]
            # Try to search by name, state, City
            restaurants = get_search_results(input)
            print(restaurants)
            context = {
                "restaurants": set(restaurants),
            }
            return render(request, 'home/searchresults.html', context)
        # except:
            # print("No Restaurant found")

    restaurant_list = Restaurant.objects.all()
    featured_list = Featured.objects.all()
    context = {
        'restaurants':restaurant_list, 
        'featureds': featured_list,
        }
    return render(request, 'home/index.html', context)

def bycity(request, city):
    restaurants = Restaurant.objects.filter(city = city)
    context = {
        "restaurants": restaurants,
        "city": city,
    }
    return render(request, 'home/bycity.html', context)

def my_login(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return render(request, "home/login.html", {
                "error": "Invalid username and/or password."
            })
    else:
        return render(request, "home/login.html")

@login_required
def my_logout(request):
    logout(request)
    return redirect("/")

def restaurant(request, name):
    try:
        restaurant = Restaurant.objects.get(name = name)
        context = {
            'restaurant': restaurant,
        }
        return render(request, 'home/restaurant.html', context)
    except:
        return render(request, 'home/404.html')

def my_signup(request):

    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["password2"]
        if password != confirmation:
            return render(request, "home/signup.html", {
                "error": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.set_password(password)
            user.is_active=True
            user.is_staff=True
            user.save()
        except IntegrityError:
            return render(request, "home/signup.html", {
                "error": "Username already taken."
            })
        login(request, user)
        return redirect("/")
    else:
        return render(request, "home/signup.html")


@login_required
def view_profile(request):
    try:
        profile = Profile.objects.get_or_create(user = request.user)[0]
    except Exception as e:
        print("Following error occured :", e)
    return render(request, 'home/view_profile.html')


@login_required
def edit_profile(request):
    user = request.user
    if request.method == "POST":
        try:
            profile = Profile.objects.get_or_create(user = request.user)[0]
        except Exception as e:
            print("Following error occured :", e)
        if request.FILES:
            image = request.FILES["image"]
            profile.image = image
            profile.save()
        if request.POST["username"]:
            username = request.POST["username"]
            user.username = username
            user.save()
        if request.POST["email"]:
            email = request.POST["email"]
            user.email = email
            user.save()
        return render(request, 'home/view_profile.html')
        
    else:
        profile = Profile.objects.get_or_create(user = request.user)[0]
        context = {
            "profile":profile
        }
        return render(request, 'home/edit_profile.html', context)


@login_required
def delete_profile(request):
    try:
        user = User.objects.get(username = request.user.username)
        user.delete()
    except Exception as e:
        print("User delete error is ", e)
        logout(request)
        return render(request, 'home/login.html')
    return redirect("/")

home/templates/home/bycity.html
{% extends 'home/layout.html' %}
{% load static %}

{% block title %}
GoParty | City
{% endblock %}

{% block navbar %}
<!-- Navbar 2 Starts -->
<nav class="navbar navbar-expand-lg navbar-light"  style="background-color: #e3f2fd;">
    <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1"
    aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="dark-blue-text"><i
        class="fas fa-bars fa-1x"></i></span></button>
    <div class="container-fluid d-flex">
      <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent1">
        <ul class="navbar-nav">
          {% for city in cities %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:bycity' city %}">{{ city }}</a>
          </li>
          {% endfor %}
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">City 2</a>
          </li> -->
        </ul>
      </div>
    </div>
  </nav>
  <!-- Navbar 2 Ends -->
  {% endblock %}

{% block body %}
<div class="card bg-dark text-white" style="min-height: 40rem;">
    <div class="d-flex justify-content-center">
        <div class="card-header">
            <h1>{{ city }}</h1>
        </div>
    </div>
    <!-- <div class="container d-flex justify-content-center">
        <ul>
            {% for restaurant in restaurants %}

            <li><h3><a href="{% url 'home:restaurant' restaurant.name %}">{{ restaurant }}</a></h3></li>
            {% endfor %}           
        </ul>
    </div> -->
<div class="card-deck m-1">
{% for restaurant in restaurants %}
    <div class="card bg-primary">
    {% with restaurant.images.all|first as image %}                    
        <img class="card-img-top img-thumbnail" src="{{ image.image.url }}" alt="Card image cap" style="max-height: 25rem;">
    {% endwith %}
    <a href="{% url 'home:restaurant' restaurant.name %}">
        <div class="card-body">
        <h5 class="card-title font-weight-bold"><a class="text-dark" href="{% url 'home:restaurant' restaurant.name %}">{{ restaurant }}</a></h5>
        </div>
    </a>
    </div>                
{% endfor %}
</div>
</div>

{% endblock %}

home/templates/home/edit_profile.html
{% extends 'home/layout.html' %}
{% load static %}

{% block title %}
GoParty | Edit Profile
{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'home.css' %}">
<div class="card text-white bg-info m-auto my-2" style="max-width: 23.5rem;">
    <div class="card-header font-weight-bold text-center">
        <h1>Edit Profile</h1>
    </div>
    <form action="{% url 'home:edit_profile' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="card-body col-lg-12 col-md-12 col-sm-12 form-group">
          <img src="{{ profile.image.url }}" height="330" width="330" alt="" class="row-12 img-thumbnail">
          <div class="custom-file">
            <input type="file" class="form-control-file" id="exampleFormControlFile1" name="image">
          </div>
          <input type="text" name="username" id="username" class="row-12 form-control" value="{{ user.username }}" placeholder="Username">
          <input type="email" name="email" id="email" class="row-12 form-control" value="{{ user.email }}" placeholder="Email">
          <div class="row-12 d-flex justify-content-between">
              <button type="submit" class="btn btn-success col-md-6 col-sm-12">Submit</button>
              <a href="{% url 'home:index' %}" class="btn btn-warning col-md-6 col-sm-12">Cancel</a>
          </div>
          <a href="{% url 'home:delete_profile' %}" class="btn btn-danger col-lg-12 col-md-12 col-sm-12 d-flex justify-content-center">Delete Profile</a>
        </div>
    </form>
</div>
{% endblock %}

home/templates/home/index.html
{% extends 'home/layout.html' %}
{% load static %}

{% block title %}
GoParty | Home
{% endblock %}

{% block navbar %}
<!-- Navbar 2 Starts -->
<nav class="navbar navbar-expand-lg navbar-light"  style="background-color: #e3f2fd;">
    <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1"
    aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="dark-blue-text"><i
        class="fas fa-bars fa-1x"></i></span></button>
    <div class="container-fluid d-flex">
      <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent1">
        <ul class="navbar-nav">
          {% for city in cities %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:bycity' city %}">{{ city }}</a>
          </li>
          {% endfor %}
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">City 2</a>
          </li> -->
        </ul>
      </div>
    </div>
  </nav>
  <!-- Navbar 2 Ends -->

  <!-- Navbar 3 Starts -->
  <nav class="navbar navbar-expand-lg navbar-light col-12" style="background: url({% static 'searchbarbanner.png' %});">
    <div class="col-12">
      <div class="row-12">
        <h1 class="font-weight-bold d-flex justify-content-center m-1 p-1 text-white">Over 11 Restaurants in More than 1 City</h1>
      </div>
      <div class="row-12">
        <form method="post">
          <div class="input-group input-group-lg p-3 row-lg-12">
            {% csrf_token %}
            <input type="text" name="input" aria-label="Search" placeholder="Search by city, state or neighbourhood" class="form-control col-lg-8" required />
            <!-- <input type="text" name="datetime" class="col-lg-2" placeholder="Start Date and Time" onfocus="(this.type='datetime-local')" onblur="if(this.value==''){this.type='text'}" required> -->
            {% if request.user.is_authenticated %}
            <button type="submit" class="form-control btn btn-primary col-lg-2">Search</button>
            {% else %}
            <a class="form-control btn btn-primary col-lg-2" href="{% url 'home:login' %}">Search</a>
            {% endif %}
            
          </div>
        </form>
      </div>
    </div>
  </nav>
  <!-- Navbar 3 Ends -->
{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'home.css' %}">
<h1 class="font-weight-bold text-center">Featured Restaurants</h1>
  <div class="row ml-1" style="overflow-x: auto; flex-wrap: nowrap;">
      {% for restaurant in featureds %}
        <div class="card col-lg-3 col-md-4 col-sm-6 mx-1 p-0">
          {% with restaurant.restaurant.images.all|first as image %}
          <img class="card-img-top img-thumbnail" src="{{ image.image.url }}" alt="Card image cap" style="height: 19rem;">
          {% endwith %}
          
          <div class="card-body">
            <a href="{% url 'home:restaurant' restaurant.restaurant.name %}" class="card-title font-weight-bold">{{ restaurant.restaurant.name }}</a>
            <h5 class="font-weight-bold">₹{{ restaurant.restaurant.price }}</h5>
            <!-- <p class="card-text">{{ restaurant.restaurant.address }}</p> -->
            <!-- <p class="card-text font-weight-bold">Features: </p>
            <ul>
              {% if restaurant.restaurant.features.great_food %}
              <li class="card-text">Great Food</li>
              {% endif %}
              {% if restaurant.restaurant.features.satisfactory_staff %}
              <li class="card-text">Statisfactory Staff</li>
              {% endif %}
              {% if restaurant.restaurant.features.great_ambience %}
              <li class="card-text">Great Ambience</li>
              {% endif %}
              {% if restaurant.restaurant.features.good_service %}
              <li class="card-text">Good Service</li>
              {% endif %}
              {% if restaurant.restaurant.features.reasonable_cost %}
              <li class="card-text">Reasonable Cost</li>
              {% endif %}
              {% if restaurant.restaurant.features.hygiene_and_cleanliness %}
              <li class="card-text">Hygiene And Cleanliness</li>
              {% endif %}
            </ul> -->
          </div>
          <!-- <div class="card-footer">
            <p class="card-text"><small class="text-muted">Last Updated {{ restaurant.restaurant.edited }}</small></p>
          </div> -->
        </div>
      {% endfor %}
  </div>

<h1 class="font-weight-bold text-center">Restaurants</h1>
<!-- <div class="row ml-1" style="display: flex; overflow: auto; flex-wrap: nowrap;">
  {% for restaurant in restaurants %}
    <div class="card col-lg-3 col-md-4 col-sm-12 bg-dark text-white mr-1 mb-1 p-0">
      {% with restaurant.images.all|first as image %}
      <img class="card-img" src="{{ image.image.url }}" alt="Card image" style="height:17rem;">
      {% endwith %}
        <div class="card-img-overlay">
          <h5 class="card-title">
            <a href="{% url 'home:restaurant' restaurant.name %}" class="card-title font-weight-bold">{{ restaurant.name }}</a>
          </h5>
          <p class="card-text">₹{{ restaurant.price }}</p>
        </div>
    </div>
  {% endfor %}
</div> -->
<div class="row ml-1 mb-1" style="overflow-x: auto; flex-wrap: nowrap;">
  {% for restaurant in restaurants|slice:"0:6" %}
  <div class="bg-image hover-overlay ripple shadow-1-strong rounded col-lg-3 col-md-4 col-sm-12" data-mdb-ripple-color="light">
    {% with restaurant.images.all|first as image %}
    <img src="{{ image.image.url }}" alt="Louvre" style="height: 20rem; width: 100%;"/>
    {% endwith %}
    <a class="text-white" href="{% url 'home:restaurant' restaurant.name %}">
      <div class="mask text-center font-weight-bold" style="background-color: rgba(251, 251, 251, 0.2)"><h1>{{ restaurant.name }}</h1></div>
    </a>
  </div>
  {% endfor %}
</div>

{% endblock %}

home/templates/home/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>

    <link rel="stylesheet" href="{% static 'css/my.css' %}">
    <script src="{% static 'js/my.js' %}"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Google Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Login CDN's -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
<!-- MDB Import Starts -->
   <!-- Font Awesome -->
   <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
   <!-- Google Fonts -->
   <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
   <!-- MDB -->
   <link
   href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css"
   rel="stylesheet"
   />
       <!-- MDB Import Ends -->
    
    <title>
      {% block title %}
      {% endblock %}
    </title>

    <!-- Nabvar 1 Starts -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light d-flex">
      <div class="d-flex mr-auto">
        <a class="navbar-brand font-weight-bold" href="{% url 'home:index' %}"><img src="{% static 'logo.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-top"> GoParty</a>
        <!-- {% block navbarsearchtab %}
        <h1 class="d-flex mr-3">Hi</h1>
        {% endblock %} -->
        <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="dark-blue-text">
            <i class="fas fa-bars fa-1x"></i>
          </span>
        </button>
            
      </div>
      <div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item d-flex justify-content-center">
              <a class="nav-link d-flex" href="{% url 'home:view_profile' %}">
                {% if user.profile.image.url %}
                <img src="{{ user.profile.image.url }}" width="30" height="30" class="rounded-circle">
                {% else %}
                <span class="material-icons">person</span>
                {% endif %}
                <span class="justify-content-center">&nbsp;{{ user.username }}</span>
              </a>
            </li>
            <li class="nav-item d-flex justify-content-center">
              <a class="nav-link d-flex" href="{% url 'home:logout' %}">
                <span class="material-icons">logout</span>
                <span class="justify-content-center">Logout</span>
              </a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link d-flex" href="{% url 'home:login' %}">
                <span class="material-icons">login</span>
                <span class="justify-content-center">Login</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex" href="{% url 'home:signup' %}">
                <span class="material-icons">edit</span>
                <span class="justify-content-center">Sign Up</span>
              </a>
            </li>
            {% endif %}
            
          </ul>
        </div>
      </div>
    </nav>
    <!-- Navbar 1 Ends -->

    

    {% block navbar %}
    {% endblock %}

  </head>
  <body>
    {% block body %}
    {% endblock %}
    <!-- Footer Starts -->
    
<footer class="text-white text-center text-lg-start" style="background-color: rgb(13, 138, 96);">
  <nav class="nav navbar-nav">

    <!-- Grid container -->
    <div class="container p-4">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
          <h5 class="text-uppercase">GoParty</h5>
  
          <p>
            Best Restaurants for Partying and renting at cheap rates for 2 Hours found here
          </p>
        </div>
        <!--Grid column-->
  
        <!--Grid column-->
        {% for city in cities %}
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase"><a class="nav-link text-white" href="{% url 'home:bycity' city %}">{{ city }}</a></h5>
  
          <!-- <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">Restaurant 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Restaurant 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Restaurant 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Restaurant 4</a>
            </li>
          </ul> -->
          
        </div>
        {% endfor %}
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Grid container -->
  </nav>
</footer>
    <!-- Footer Ends -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/login.html
{% extends 'home/layout.html' %}
{% load static %}

{% block title %}
GoParty | Login
{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'home.css' %}">
{% if success %}
<div class="container">
    <div class="alert alert-success" role="alert">{{ success }}</div>
</div>
{% endif %}
{% if error %}
<div class="container">
    <div class="alert alert-danger" role="alert">{{ error }}</div>
</div>
{% endif %}
{% if message %}
<div class="container">
    <div class="alert alert-primary" role="alert">{{ message }}</div>
</div>
{% endif %}
    <div class="wrapper">
        <div class="logo">
            <img src="{% static 'logo.png' %}" alt="">
        </div>
        <div class="text-center mt-4 name">
            Login to GoParty
        </div>
        <form class="p-3 mt-3" action="{% url 'home:login' %}" method="post">
            {% csrf_token %}
            <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                <input type="text" name="username" id="username" placeholder="Username">
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                <input type="password" name="password" id="pwd" placeholder="Password">
            </div>
            <button type="submit" class="btn mt-3">Login</button>
        </form>
        <div class="text-center fs-6">
            <a href="{% url 'home:signup' %}">New User?</a> instead <a href="{% url 'home:signup' %}">Sign up</a>
        </div>
    </div>
{% endblock %}

home/templates/home/searchresults.html
{% extends 'home/layout.html' %}
{% load static %}

{% block title %}
GoParty | Search Results
{% endblock %}

{% block navbar %}
<!-- Navbar 2 Starts -->
<nav class="navbar navbar-expand-lg navbar-light"  style="background-color: #e3f2fd;">
    <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1"
    aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="dark-blue-text"><i
        class="fas fa-bars fa-1x"></i></span></button>
    <div class="container-fluid d-flex">
      <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent1">
        <ul class="navbar-nav">
          {% for city in cities %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:bycity' city %}">{{ city }}</a>
          </li>
          {% endfor %}
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">City 2</a>
          </li> -->
        </ul>
      </div>
    </div>
  </nav>
  <!-- Navbar 2 Ends -->

  {% endblock %}

  {% block body %}
  <div class="card bg-dark text-white" style="min-height: 40rem;">
    <div class="d-flex justify-content-center">
        <div class="card-header">
            <h1>{{ city }}</h1>
        </div>
    </div>
    {% if restaurants %}
    <div class="container d-flex justify-content-center">
        <ul>
            {% for restaurant in restaurants %}

            <li><h3><a href="{% url 'home:restaurant' restaurant.name %}">{{ restaurant }}</a></h3></li>
            {% endfor %}           
        </ul>
    </div>
    {% else %}
    <h1>No Restaurants Nearby</h1>
    {% endif %}
</div>
  {% endblock %}

home/templates/home/view_profile.html
{% extends 'home/layout.html' %}
{% load static %}

{% block title %}
GoParty | Profile
{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'home.css' %}">
<div class="card text-white bg-info m-auto my-2" style="max-width: 23.5rem;">
    <div class="card-header font-weight-bold text-center">
        <h1>Profile</h1>
    </div>
    <div class="card-body col-lg-12 col-md-12 col-sm-12">
      <img src="{{ user.profile.image.url }}" height="330" width="330" alt="" class="row-12 img-thumbnail">
      <h5 class="card-title row-12 text-center m-2">{{ user.username }}</h5>
      <h5 class="card-title row-12 text-center m-2">{{ user.email }}</h5>
      <a href="{% url 'home:edit_profile' %}" class="btn btn-warning row-12 d-flex justify-content-center">Edit</a>
    </div>
</div>
{% endblock %}